<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-11-18T16:15:33 IST" name="Suite" finished-at="2023-11-18T16:15:56 IST" duration-ms="22865">
    <groups>
    </groups>
    <test started-at="2023-11-18T16:15:33 IST" name="Test" finished-at="2023-11-18T16:15:56 IST" duration-ms="22865">
      <class name="testClass.GetEpayAddNewSubjectTest">
        <test-method is-config="true" signature="loadConfig()[pri:0, instance:testClass.GetEpayAddNewSubjectTest@306e95ec]" started-at="2023-11-18T16:15:32 IST" name="loadConfig" finished-at="2023-11-18T16:15:33 IST" duration-ms="757" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadConfig -->
        <test-method is-config="true" signature="BeforeMethod()[pri:0, instance:testClass.GetEpayAddNewSubjectTest@306e95ec]" started-at="2023-11-18T16:15:33 IST" name="BeforeMethod" finished-at="2023-11-18T16:15:43 IST" duration-ms="9803" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method signature="addSubject()[pri:0, instance:testClass.GetEpayAddNewSubjectTest@306e95ec]" started-at="2023-11-18T16:15:43 IST" name="addSubject" finished-at="2023-11-18T16:15:55 IST" duration-ms="12158" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:751)
at org.testng.Assert.assertEquals(Assert.java:761)
at pageObjectsPOM.GetEpayAddNewSubject.verifySuccessPopup(GetEpayAddNewSubject.java:95)
at testClass.GetEpayAddNewSubjectTest.addSubject(GetEpayAddNewSubjectTest.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addSubject -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testClass.GetEpayAddNewSubjectTest@306e95ec]" started-at="2023-11-18T16:15:55 IST" name="tearDown" finished-at="2023-11-18T16:15:56 IST" duration-ms="558" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="aftersuite()[pri:0, instance:testClass.GetEpayAddNewSubjectTest@306e95ec]" started-at="2023-11-18T16:15:56 IST" name="aftersuite" finished-at="2023-11-18T16:15:57 IST" duration-ms="1317" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftersuite -->
      </class> <!-- testClass.GetEpayAddNewSubjectTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
